"use client";

import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export function NewProductForm() {
  const router = useRouter(); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); setSaving(true); const form = new FormData(event.currentTarget); const payload = Object.fromEntries(form); payload.price = Number(payload.price); payload.stock = Number(payload.stock); const response = await fetch("/api/admin/products", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); setSaving(false); const body = await response.json().catch(() => null); if (!response.ok) { setMessage(body?.error ?? "Enregistrement impossible."); return; } router.push("/shop"); router.refresh(); }
  return <section className="product-form-wrap"><div><p className="eyebrow">Catalogue</p><h1>Ajouter un article</h1><p>Utilisez l’URL publique générée par votre bucket Cloudflare R2/S3. Les clés d’accès ne sont jamais saisies ici.</p></div><form onSubmit={submit} className="product-form"><label>Nom de l’article<input name="name" required maxLength={140} placeholder="Ex. Blush crème Sun Kiss" /></label><label>Catégorie<input name="category" required list="categories" placeholder="Teint, Joues, Soin…" /><datalist id="categories"><option value="Teint"/><option value="Joues"/><option value="Soin"/></datalist></label><label>Prix (€)<input name="price" required type="number" min="0" step="0.01" placeholder="29,00" /></label><label>SKU<input name="sku" required pattern="[A-Za-z0-9_-]+" placeholder="KIM-BLUSH-001" /></label><label>Stock initial<input name="stock" required type="number" min="0" step="1" placeholder="30" /></label><label>Statut<select name="status"><option value="PUBLISHED">Publié</option><option value="DRAFT">Brouillon</option></select></label><label className="form-span">URL image (R2/S3)<input name="imageUrl" required type="url" placeholder="https://cdn.votredomaine.com/produits/blush.jpg" /></label><label className="form-span">Description<textarea name="description" rows={5} placeholder="Présentez la texture, les bénéfices et les teintes." /></label>{message && <p className="form-message" role="alert">{message}</p>}<button disabled={saving} className="button button-dark form-span">{saving ? "Enregistrement…" : "Créer l’article"} <span>→</span></button></form></section>;
}
