"use client";

import { ChangeEvent, FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export function NewProductForm() {
  const router = useRouter(); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false); const [image, setImage] = useState<File | null>(null); const [preview, setPreview] = useState("");
  function selectImage(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0] ?? null; setImage(file); setPreview(file ? URL.createObjectURL(file) : ""); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!image) { setMessage("Ajoutez une photo du produit."); return; } setMessage(""); setSaving(true); const form = new FormData(event.currentTarget); const upload = new FormData(); upload.set("image", image); const uploadResponse = await fetch("/api/admin/uploads", { method: "POST", body: upload }); const uploadBody = await uploadResponse.json().catch(() => null); if (!uploadResponse.ok) { setSaving(false); setMessage(uploadBody?.error ?? "Impossible d’ajouter la photo."); return; } const payload = { ...Object.fromEntries(form), price: Number(form.get("price")), stock: Number(form.get("stock")), imageUrl: uploadBody.url }; const response = await fetch("/api/admin/products", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); setSaving(false); const body = await response.json().catch(() => null); if (!response.ok) { setMessage(body?.error ?? "Enregistrement impossible."); return; } router.push("/shop"); router.refresh(); }
  return <section className="product-form-wrap"><div><p className="eyebrow">Catalogue</p><h1>Ajouter un article</h1><p>Créez votre fiche et ajoutez directement une photo. Elle sera envoyée dans votre stockage Cloudflare R2/S3.</p></div><form onSubmit={submit} className="product-form"><label>Nom de l’article<input name="name" required maxLength={140} placeholder="Ex. Blush crème Sun Kiss" /></label><label>Catégorie<input name="category" required list="categories" placeholder="Teint, Joues, Soin…" /><datalist id="categories"><option value="Teint"/><option value="Joues"/><option value="Soin"/></datalist></label><label>Prix (€)<input name="price" required type="number" min="0" step="0.01" placeholder="29,00" /></label><label>SKU<input name="sku" required pattern="[A-Za-z0-9_-]+" placeholder="SIM-BLUSH-001" /></label><label>Stock initial<input name="stock" required type="number" min="0" step="1" placeholder="30" /></label><label>Statut<select name="status"><option value="PUBLISHED">Publié</option><option value="DRAFT">Brouillon</option></select></label><label className="form-span photo-upload">Photo du produit<input required type="file" accept="image/jpeg,image/png,image/webp" onChange={selectImage} /><span>{image ? image.name : "Choisir une photo"}</span>{preview && <img src={preview} alt="Aperçu du produit" />}</label><label className="form-span">Description<textarea name="description" rows={5} placeholder="Présentez la texture, les bénéfices et les teintes." /></label>{message && <p className="form-message" role="alert">{message}</p>}<button disabled={saving} className="button button-dark form-span">{saving ? "Enregistrement…" : "Créer l’article"} <span>→</span></button></form></section>;
}
