import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const users = sqliteTable("users", { id: text("id").primaryKey(), email: text("email").notNull().unique(), role: text("role", { enum: ["CUSTOMER", "STAFF", "ADMIN"] }).notNull().default("CUSTOMER"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const products = sqliteTable("products", { id: text("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull().unique(), status: text("status", { enum: ["DRAFT", "PUBLISHED", "ARCHIVED"] }).notNull().default("DRAFT"), description: text("description"), lowStockThreshold: integer("low_stock_threshold").notNull().default(8), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const productVariants = sqliteTable("product_variants", { id: text("id").primaryKey(), productId: text("product_id").notNull().references(() => products.id), sku: text("sku").notNull().unique(), priceCents: integer("price_cents").notNull(), compareAtPriceCents: integer("compare_at_price_cents"), costCents: integer("cost_cents"), stock: integer("stock").notNull().default(0) });
export const inventoryMovements = sqliteTable("inventory_movements", { id: text("id").primaryKey(), variantId: text("variant_id").notNull().references(() => productVariants.id), quantity: integer("quantity").notNull(), type: text("type", { enum: ["PURCHASE", "SALE", "RETURN", "REFUND", "CORRECTION", "LOSS", "DAMAGE", "MANUAL"] }).notNull(), reason: text("reason").notNull(), actorId: text("actor_id").references(() => users.id), reference: text("reference"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const orders = sqliteTable("orders", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id), status: text("status", { enum: ["PENDING", "AWAITING_PAYMENT", "PAID", "PROCESSING", "SHIPPED", "DELIVERED", "CANCELLED", "REFUNDED"] }).notNull(), subtotalCents: integer("subtotal_cents").notNull(), totalCents: integer("total_cents").notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const orderItems = sqliteTable("order_items", { id: text("id").primaryKey(), orderId: text("order_id").notNull().references(() => orders.id), variantId: text("variant_id").references(() => productVariants.id), titleSnapshot: text("title_snapshot").notNull(), skuSnapshot: text("sku_snapshot"), unitPriceCents: integer("unit_price_cents").notNull(), quantity: integer("quantity").notNull() });
export const expenses = sqliteTable("expenses", { id: text("id").primaryKey(), category: text("category").notNull(), amountCents: integer("amount_cents").notNull(), supplier: text("supplier"), note: text("note"), incurredAt: integer("incurred_at", { mode: "timestamp" }).notNull() });
