import { index, integer, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

const timestamps = {
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
};

export const users = sqliteTable("users", {
  id: text("id").primaryKey(), email: text("email").notNull(), name: text("name"), role: text("role", { enum: ["CUSTOMER", "STAFF", "ADMIN"] }).notNull().default("CUSTOMER"), passwordHash: text("password_hash"), passwordSalt: text("password_salt"), isActive: integer("is_active", { mode: "boolean" }).notNull().default(true), ...timestamps,
}, (table) => [uniqueIndex("users_email_unique").on(table.email)]);

export const adminSessions = sqliteTable("admin_sessions", {
  id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), expiresAt: integer("expires_at", { mode: "timestamp" }).notNull(), createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
}, (table) => [index("admin_sessions_user_id_idx").on(table.userId), index("admin_sessions_expires_at_idx").on(table.expiresAt)]);

export const categories = sqliteTable("categories", { id: text("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull(), description: text("description"), imageUrl: text("image_url"), sortOrder: integer("sort_order").notNull().default(0), isPublished: integer("is_published", { mode: "boolean" }).notNull().default(true), ...timestamps }, (table) => [uniqueIndex("categories_slug_unique").on(table.slug)]);
export const collections = sqliteTable("collections", { id: text("id").primaryKey(), name: text("name").notNull(), slug: text("slug").notNull(), description: text("description"), heroImageUrl: text("hero_image_url"), isPublished: integer("is_published", { mode: "boolean" }).notNull().default(false), ...timestamps }, (table) => [uniqueIndex("collections_slug_unique").on(table.slug)]);
export const products = sqliteTable("products", { id: text("id").primaryKey(), categoryId: text("category_id").references(() => categories.id, { onDelete: "set null" }), name: text("name").notNull(), slug: text("slug").notNull(), description: text("description"), status: text("status", { enum: ["DRAFT", "PUBLISHED", "ARCHIVED"] }).notNull().default("DRAFT"), featured: integer("featured", { mode: "boolean" }).notNull().default(false), lowStockThreshold: integer("low_stock_threshold").notNull().default(8), ...timestamps }, (table) => [uniqueIndex("products_slug_unique").on(table.slug), index("products_category_id_idx").on(table.categoryId), index("products_status_idx").on(table.status)]);
export const collectionProducts = sqliteTable("collection_products", { collectionId: text("collection_id").notNull().references(() => collections.id, { onDelete: "cascade" }), productId: text("product_id").notNull().references(() => products.id, { onDelete: "cascade" }), sortOrder: integer("sort_order").notNull().default(0) }, (table) => [uniqueIndex("collection_products_unique").on(table.collectionId, table.productId)]);
export const productVariants = sqliteTable("product_variants", { id: text("id").primaryKey(), productId: text("product_id").notNull().references(() => products.id, { onDelete: "cascade" }), title: text("title").notNull(), sku: text("sku").notNull(), priceCents: integer("price_cents").notNull(), compareAtPriceCents: integer("compare_at_price_cents"), costCents: integer("cost_cents"), stock: integer("stock").notNull().default(0), attributesJson: text("attributes_json"), ...timestamps }, (table) => [uniqueIndex("product_variants_sku_unique").on(table.sku), index("product_variants_product_id_idx").on(table.productId)]);
export const productImages = sqliteTable("product_images", { id: text("id").primaryKey(), productId: text("product_id").notNull().references(() => products.id, { onDelete: "cascade" }), variantId: text("variant_id").references(() => productVariants.id, { onDelete: "set null" }), url: text("url").notNull(), altText: text("alt_text"), position: integer("position").notNull().default(0), isPrimary: integer("is_primary", { mode: "boolean" }).notNull().default(false), ...timestamps }, (table) => [index("product_images_product_id_idx").on(table.productId)]);
export const inventoryMovements = sqliteTable("inventory_movements", { id: text("id").primaryKey(), variantId: text("variant_id").notNull().references(() => productVariants.id, { onDelete: "cascade" }), quantity: integer("quantity").notNull(), type: text("type", { enum: ["PURCHASE", "SALE", "RETURN", "REFUND", "CORRECTION", "LOSS", "DAMAGE", "MANUAL"] }).notNull(), reason: text("reason").notNull(), actorId: text("actor_id").references(() => users.id, { onDelete: "set null" }), orderId: text("order_id"), reference: text("reference"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() }, (table) => [index("inventory_movements_variant_id_idx").on(table.variantId)]);
export const addresses = sqliteTable("addresses", { id: text("id").primaryKey(), userId: text("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), label: text("label"), firstName: text("first_name").notNull(), lastName: text("last_name").notNull(), line1: text("line1").notNull(), line2: text("line2"), city: text("city").notNull(), postalCode: text("postal_code").notNull(), country: text("country").notNull(), phone: text("phone"), isDefault: integer("is_default", { mode: "boolean" }).notNull().default(false), ...timestamps });
export const carts = sqliteTable("carts", { id: text("id").primaryKey(), userId: text("user_id").references(() => users.id, { onDelete: "cascade" }), sessionKey: text("session_key"), currency: text("currency").notNull().default("EUR"), ...timestamps });
export const cartItems = sqliteTable("cart_items", { id: text("id").primaryKey(), cartId: text("cart_id").notNull().references(() => carts.id, { onDelete: "cascade" }), variantId: text("variant_id").notNull().references(() => productVariants.id, { onDelete: "cascade" }), quantity: integer("quantity").notNull(), ...timestamps }, (table) => [uniqueIndex("cart_items_variant_unique").on(table.cartId, table.variantId)]);
export const orders = sqliteTable("orders", { id: text("id").primaryKey(), orderNumber: text("order_number").notNull(), userId: text("user_id").references(() => users.id, { onDelete: "set null" }), email: text("email").notNull(), status: text("status", { enum: ["PENDING", "AWAITING_PAYMENT", "PAID", "PROCESSING", "SHIPPED", "DELIVERED", "CANCELLED", "REFUNDED"] }).notNull().default("PENDING"), currency: text("currency").notNull().default("EUR"), subtotalCents: integer("subtotal_cents").notNull(), discountCents: integer("discount_cents").notNull().default(0), shippingCents: integer("shipping_cents").notNull().default(0), taxCents: integer("tax_cents").notNull().default(0), totalCents: integer("total_cents").notNull(), shippingAddressJson: text("shipping_address_json"), ...timestamps }, (table) => [uniqueIndex("orders_order_number_unique").on(table.orderNumber), index("orders_user_id_idx").on(table.userId)]);
export const orderItems = sqliteTable("order_items", { id: text("id").primaryKey(), orderId: text("order_id").notNull().references(() => orders.id, { onDelete: "cascade" }), variantId: text("variant_id").references(() => productVariants.id, { onDelete: "set null" }), titleSnapshot: text("title_snapshot").notNull(), skuSnapshot: text("sku_snapshot"), imageUrlSnapshot: text("image_url_snapshot"), unitPriceCents: integer("unit_price_cents").notNull(), quantity: integer("quantity").notNull(), ...timestamps });
export const payments = sqliteTable("payments", { id: text("id").primaryKey(), orderId: text("order_id").notNull().references(() => orders.id, { onDelete: "cascade" }), provider: text("provider").notNull(), providerReference: text("provider_reference"), status: text("status", { enum: ["PENDING", "AUTHORIZED", "PAID", "FAILED", "REFUNDED"] }).notNull().default("PENDING"), amountCents: integer("amount_cents").notNull(), currency: text("currency").notNull(), idempotencyKey: text("idempotency_key").notNull(), ...timestamps }, (table) => [uniqueIndex("payments_idempotency_unique").on(table.idempotencyKey)]);
export const discounts = sqliteTable("discounts", { id: text("id").primaryKey(), code: text("code").notNull(), type: text("type", { enum: ["PERCENTAGE", "FIXED"] }).notNull(), value: integer("value").notNull(), minimumCents: integer("minimum_cents"), startsAt: integer("starts_at", { mode: "timestamp" }), endsAt: integer("ends_at", { mode: "timestamp" }), maxUses: integer("max_uses"), usesCount: integer("uses_count").notNull().default(0), isActive: integer("is_active", { mode: "boolean" }).notNull().default(true), ...timestamps }, (table) => [uniqueIndex("discounts_code_unique").on(table.code)]);
export const expenses = sqliteTable("expenses", { id: text("id").primaryKey(), category: text("category").notNull(), description: text("description").notNull(), amountCents: integer("amount_cents").notNull(), supplier: text("supplier"), receiptUrl: text("receipt_url"), incurredAt: integer("incurred_at", { mode: "timestamp" }).notNull(), ...timestamps });
export const auditLogs = sqliteTable("audit_logs", { id: text("id").primaryKey(), actorId: text("actor_id").references(() => users.id, { onDelete: "set null" }), action: text("action").notNull(), resourceType: text("resource_type").notNull(), resourceId: text("resource_id"), beforeJson: text("before_json"), afterJson: text("after_json"), createdAt: integer("created_at", { mode: "timestamp" }).notNull() });
export const storeSettings = sqliteTable("store_settings", { id: text("id").primaryKey(), storeName: text("store_name").notNull(), currency: text("currency").notNull().default("EUR"), logoUrl: text("logo_url"), legalText: text("legal_text"), taxRateBasisPoints: integer("tax_rate_basis_points").notNull().default(0), defaultLowStockThreshold: integer("default_low_stock_threshold").notNull().default(8), socialsJson: text("socials_json"), ...timestamps });
